vision_network:
  task: detection
  model: faster_rcnn_X_101_32x8d_FPN_3x

filtering_network:
  architecture:
    normalization: 'cn'
    feature_modulation: false
  train: true
  optimizer:
    name: adam
    learning_rate: 1e-4
    scheduler: exponential
    final_lr_ratio: 1e-1

codec:
  name: surrogate
  quality: 6

lmbda:
  mode: single
  log2_lmbda: 1

control_input: none